apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: crossplane-eks-demo-05
  annotations:
    github.com/project-slug: gy-org/crossplane-eks-demo-05
    links:
      - url: https://dashboard.example.com
        title: My Dashboard
        icon: dashboard
  description: crossplane-eks-demo-05 created by Crossplane
  links:
    - url: https://dashboard.example.com
      title: My Dashboard
      icon: dashboard
spec:
  type: cluster
  owner: user:guest
  lifecycle: experimental
