name: Create Amazon EKS
permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      clusterName:
        description: ' The name of your EKS cluster'
        required: true
      region:
        description: 'The AWS region where the cluster will be deployed'
        required: true
      version:
        description: 'EKS version'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws-region: us-east-1
          
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


      - name: Create new EKS Cluster using Crossplane
        run: |
          export CLUSTER_NAME=${{ github.event.inputs.clusterName }}
          export VERSION=${{ github.event.inputs.version }}
          export REGION=${{ github.event.inputs.region }}
          role=$(aws sts assume-role --role-arn arn:aws:iam::625011733915:role/idp-demo --role-session-name my-seesion-test1)
          export AWS_ACCESS_KEY_ID=$(echo $role | jq -r .Credentials.AccessKeyId)
          export AWS_SECRET_ACCESS_KEY=$(echo $role | jq -r .Credentials.SecretAccessKey)
          export AWS_SESSION_TOKEN=$(echo $role | jq -r .Credentials.SessionToken)
          aws eks update-kubeconfig --name amp-test --region ap-northeast-1
          # envsubst < crossplane/cluster.yaml | kubectl apply -f -
          grafanaURL=kubectl get eks xplane-crossplane-eks-demo-05 -o json| jq '.status.eks.grafanaURL' 
          echo "**********"
          echo $grafanaURL
      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
    
      - name: Update catalog-info.yaml  
        run: |
          # Check if links field exists
          yq -i '.metadata.links = [{"url": $grafanaURL, "title": "Amazon Managed Grafana Dashboard URL", "icon": "grafana"}]' catalog-info.yaml
      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update catalog-info.yaml
