name: Create Amazon EKS

on:
  workflow_dispatch:
    inputs:
      clusterName:
        description: ' The name of your EKS cluster'
        required: true
      region:
        description: 'The AWS region where the cluster will be deployed'
        required: true
      version:
        description: 'EKS version'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws-region: us-east-1
          
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


      - name: Create new EKS Cluster using Crossplane
        run: |
          export CLUSTER_NAME=${{ github.event.inputs.clusterName }}
          export VERSION=${{ github.event.inputs.version }}
          export REGION=${{ github.event.inputs.region }}
          role=$(aws sts assume-role --role-arn arn:aws:iam::625011733915:role/idp-demo --role-session-name my-seesion-test1)
          export AWS_ACCESS_KEY_ID=$(echo $role | jq -r .Credentials.AccessKeyId)
          export AWS_SECRET_ACCESS_KEY=$(echo $role | jq -r .Credentials.SecretAccessKey)
          export AWS_SESSION_TOKEN=$(echo $role | jq -r .Credentials.SessionToken)
          aws eks update-kubeconfig --name amp-test --region ap-northeast-1
          envsubst < crossplane/cluster.yaml | kubectl apply -f - 